### ISSUE TITLE
Apache doesn't always start after reboot

### ISSUE THREAD

**Issue by JamesDevware** [clwdev/precip#66] opened 2017-08-11 16:38 UTC
Not sure of the cause but after a reload I will sometimes need to give apache a kick with "sudo service apache2 start"

**Comment by jeffgeorge** [comment] 2017-08-11 18:09
I almost always provision post-reload, which will ensure services are running.

**Comment by amanaplan** [comment] 2017-08-21 13:33
@jeffgeorge @Xenza  I'm also observing this issue each time I start precip (`vagrant up`) from a halted state (i.e., without a reload). Apparently, Apache starts before the Vagrant-provided default `/vagrant` synced folder is mounted (and according to `/etc/mtab`, it's mounted late), and fails to start because a `configtest` tries to validate the the first configured SSL certificate, which is not yet available at `/vagrant/ssl/...`.

Console output from `sudo service apache2 status`:

```
* apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           `-apache2-systemd.conf
   Active: failed (Result: exit-code) since Sun 2017-08-20 03:48:53 EDT; 48s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1009 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)

Aug 20 03:48:53 precip apache2[1009]: AH00112: Warning: DocumentRoot [/vagrant/util] does not exist
Aug 20 03:48:53 precip apache2[1009]: AH00112: Warning: DocumentRoot [/srv/www/d2iet/docroot] does not exist
Aug 20 03:48:53 precip apache2[1009]: AH00526: Syntax error on line 29 of /etc/apache2/sites-enabled/25-iet.vm-ssl.conf:
Aug 20 03:48:53 precip apache2[1009]: SSLCertificateFile: file '/vagrant/ssl/clwdev.vm.crt.pem' does not exist or is empty
Aug 20 03:48:53 precip apache2[1009]: Action 'configtest' failed.
Aug 20 03:48:53 precip apache2[1009]: The Apache error log may have more information.
Aug 20 03:48:53 precip systemd[1]: apache2.service: Control process exited, code=exited status=1
Aug 20 03:48:53 precip systemd[1]: Failed to start LSB: Apache2 web server.
Aug 20 03:48:53 precip systemd[1]: apache2.service: Unit entered failed state.
Aug 20 03:48:53 precip systemd[1]: apache2.service: Failed with result 'exit-code'.
```

Tail of `/etc/mtab` (current mounts):

```
10.0.0.1:/Users/cstuck/repos/precip/sites /nfs-www nfs rw,relatime,vers=3,rsize=8192,wsize=8192,namlen=255,hard,proto=udp,timeo=11,retrans=3,sec=sys,mountaddr=10.0.0.1,mountvers=3,mountport=674,mountproto=udp,local_lock=none,addr=10.0.0.1 0 0
vagrant /vagrant vboxsf rw,nodev,relatime 0 0
var_log_apache2 /var/log/apache2 vboxsf rw,nodev,relatime 0 0
etc_puppet_modules /etc/puppet/modules vboxsf rw,nodev,relatime 0 0
tmp_vagrant-puppet_environments /tmp/vagrant-puppet/environments vboxsf rw,nodev,relatime 0 0
bindfs /srv/www fuse.bindfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0
```

Can we avoid the `config-test`, configure the `apache2` `rc.d` service to run later than the 'vboxadd-service.service` `systemd` service, or change the default `/vagrant` synced folder to an NFS mount (which may or may not fix the issue, but, separately, will ensure access to that directory is more performant)?

**Comment by amanaplan** [comment] 2017-08-21 13:35
Current VirtualBox and Vagrant versions on host environment:

```
cstuckmbp:precip cstuck$ VBoxManage --version
5.1.26r117224
cstuckmbp:precip cstuck$ vagrant version
Installed Version: 1.9.7
Latest Version: 1.9.7
 
You're running an up-to-date version of Vagrant!
```

**Comment by jeffgeorge** [comment] 2017-08-21 13:37
This is likely an issue of [this script](https://github.com/clwdev/precip/blob/master/puppet/precip/templates/restart_services_once_mounted.conf.erb) no longer working in 16.04. We install it to [/etc/init](https://github.com/clwdev/precip/blob/master/puppet/precip/manifests/init.pp#L141-L145) and it probably isn't firing anymore.

**Comment by amanaplan** [comment] 2017-08-21 14:02
The Vagrant `upstart` event has had regressions introduced and then fixed in past versions of Vagrant because of a path change to the `upstart` binary in different versions of Ubuntu, so it’s possible it’s another regression.

**Comment by amanaplan** [comment] 2017-08-21 14:21
Per @jeffgeorge, the issue is that the previously mentioned [restart services once mounted script](https://github.com/clwdev/precip/blob/master/puppet/precip/templates/restart_services_once_mounted.conf.erb) is still an `upstart` script, and `upstart` is no longer available in Xenial. We need to migrate this behavior to `systemd`.

**Closed as completed** 2017-08-21 17:07 UTC

**Comment by amanaplan** [comment] 2017-08-21 17:46
@Xenza Can you do a `git pull` on master and `vagrant reload` to confirm this fix resolves the issue for you as well?
